name: ChangeLumberjack
version: 1.0.1
author: Adam Grieger
main: com.adamgrieger.changelumberjack.ChangeLumberjack
description: A Spigot/Bukkit plugin that notifies users of server changes when they connect to the server.

commands:
  cl:
    description: Main ChangeLumberjack command
    aliases: [changelumberjack, changelog]
    usage: Type "/<command> help" for a list of all ChangeLumberjack commands.

permissions:
  cl.*:
    description: Gives access to all ChangeLumberjack features
    default: op
    children:
      cl.admin.*: true
      cl.user.*: true
  cl.admin.*:
    description: Gives access to all ChangeLumberjack admin features
    default: false
    children:
      cl.admin.reload: true
      cl.admin.remove: true
  cl.user.*:
    description: Gives access to all regular user ChangeLumberjack features
    default: true
    children:
      cl.user.add: true
      cl.user.help: true
      cl.user.show: true
      cl.user.showall: true
      cl.user.showrecent: true
      cl.user.version: true